### PR TITLE
update so 1.1 should pass the tests

### PR DESCRIPTION
**Pull request by feanor12**
I tried to update the package so it passes the tests in 1.1
On my local machine(windows julia 1.1) the tests passed.
Please check if the results are still correct.

### CODE REVIEW

**Comment by feanor12** [comment]
Should now also pass for julia 1.0.

https://travis-ci.com/feanor12/Unwrap.jl

**Comment by platawiec** [comment]
Thanks for taking a look at this! The functionality in unwrap has moved to DSP.jl  (see https://github.com/JuliaDSP/DSP.jl/issues/196 https://github.com/JuliaDSP/DSP.jl/pull/201), I'll add a note in the README to make this more clear.

However, it does make sense for Unwrap to continue in case anyone would like a lighter-weight dependency, so I appreciate the updates.

Can you add a `Project.toml` file?

**Comment by feanor12** [comment]
Is all the functionality in DSP.jl? I thought only the 1D transform was contributed.

I'll add a project.toml file as well.

**Comment by feanor12** [comment]
I'm not sure what to put in the authors and the version field

**Comment by feanor12** [comment]
@platawiec is there anything still missing?

**Pull request merged**
